conda-forge/pipefunc-feedstock

recipe/meta.yaml
=> Bump to 0.7.0

recipe/meta.yaml
=> Bump to v0.10.0

README.md, recipe/meta.yaml
=> Bump to v0.12.0

recipe/meta.yaml
=> Bump to v0.13.0

recipe/meta.yaml
=> bump to 0.15.0

conda-forge.yml, recipe/meta.yaml
=> Bump to v0.22.0 and add update-grayskull bot

recipe/meta.yaml
=> Bump to 0.22.1

recipe/meta.yaml
=> Bump to 0.22.2

recipe/meta.yaml
=> Bump to v0.23.0

recipe/meta.yaml
=> Bump to 0.27.1

recipe/meta.yaml
=> Bump to 0.27.2

recipe/meta.yaml
=> Bump to 0.27.3

recipe/meta.yaml
=> Bump to 0.29.0

recipe/meta.yaml
=> Bump to pipefunc 0.30.0

recipe/meta.yaml
=> Bump to pipefunc 0.31.0

recipe/meta.yaml
=> Bump to pipefunc 0.32.0

recipe/meta.yaml
=> Bump to 0.32.1

recipe/meta.yaml
=> Bump to pipefunc 0.34.0

recipe/meta.yaml
=> Bump to pipefunc 0.35.0

recipe/meta.yaml
=> Bump to pipefunc 0.35.1

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, build-locally.py, recipe/meta.yaml
=> Bump to pipefunc 0.39.0

recipe/meta.yaml
=> Bump to pipefunc 0.40.0

recipe/meta.yaml
=> Bump to pipefunc 0.40.1

recipe/meta.yaml
=> Bump to pipefunc 0.41.1

recipe/meta.yaml
=> Bump to pipefunc 0.41.3

recipe/meta.yaml
=> Bump to pipefunc 0.42.0

recipe/meta.yaml
=> Bump to pipefunc 0.42.1

recipe/meta.yaml
=> Bump to pipefunc 0.43.0

recipe/meta.yaml
=> Bump to pipefunc 0.44.0

recipe/meta.yaml
=> Bump to pipefunc 0.45.0

recipe/meta.yaml
=> Bump to pipefunc 0.46.0

recipe/meta.yaml
=> Bump to pipefunc 0.47.2

recipe/meta.yaml
=> Bump to pipefunc 0.47.3

recipe/meta.yaml
=> Bump to pipefunc 0.48.0

recipe/meta.yaml
=> Bump to pipefunc 0.48.1

recipe/meta.yaml
=> Bump to pipefunc 0.49.0

recipe/meta.yaml
=> Bump to pipefunc 0.49.2

recipe/meta.yaml
=> Bump to pipefunc 0.49.4

recipe/meta.yaml
=> Bump to pipefunc 0.49.5

recipe/meta.yaml
=> Bump to pipefunc 0.49.6

recipe/meta.yaml
=> Bump to pipefunc 0.50.0

.ci_support/linux_64_.yaml, README.md, recipe/meta.yaml
=> Split package and add `pipefunc-extra`

recipe/meta.yaml
=> Bump to pipefunc 0.50.1

recipe/meta.yaml
=> Bump to pipefunc 0.50.3

recipe/meta.yaml
=> Bump to pipefunc 0.51.0

recipe/meta.yaml
=> Bump to pipefunc 0.51.1

.gitignore, recipe/meta.yaml
=> Bump to pipefunc 0.51.2

recipe/meta.yaml
=> bump to 0.51.3

recipe/meta.yaml
=> Bump to pipefunc 0.51.4

recipe/meta.yaml
=> Bump to pipefunc 0.52.0

recipe/meta.yaml
=> Limit zarr to <3

recipe/meta.yaml
=> Bump to pipefunc 0.52.1

recipe/meta.yaml
=> Bump to pipefunc 0.53.0

recipe/meta.yaml
=> Bump to pipefunc 0.53.2

recipe/meta.yaml
=> Bump to pipefunc 0.53.3

recipe/meta.yaml
=> Bump to pipefunc 0.54.0

recipe/meta.yaml
=> Bump to pipefunc 0.54.1

recipe/meta.yaml
=> Bump to pipefunc 0.55.0

.gitignore, pixi.toml, recipe/recipe.yaml
=> Bump to pipefunc 0.56.0

recipe/recipe.yaml
=> Bump to pipefunc 0.57.1

recipe/recipe.yaml
=> Bump to pipefunc 0.57.2

recipe/recipe.yaml
=> Bump to pipefunc 0.58.0

recipe/recipe.yaml
=> Bump to 0.60.0

.scripts/build_steps.sh, .scripts/run_docker_build.sh, build-locally.py, pixi.toml, recipe/recipe.yaml
=> Bump to pipefunc 0.61.0

recipe/recipe.yaml
=> Bump to pipefunc 0.63.0

recipe/recipe.yaml
=> Bump to pipefunc 0.64.0

recipe/recipe.yaml
=> Bump to pipefunc 0.65.0

recipe/recipe.yaml
=> Bump to pipefunc 0.66.0

recipe/recipe.yaml
=> Bump to pipefunc 0.67.0

recipe/recipe.yaml
=> Bump to pipefunc 0.68.0

recipe/recipe.yaml
=> Bump to pipefunc 0.70.0

recipe/recipe.yaml
=> Bump to pipefunc 0.74.0

recipe/recipe.yaml
=> Bump to 0.75.0

pixi.toml, recipe/recipe.yaml
=> Bump to pipefunc 0.78.0

recipe/recipe.yaml
=> Bump to pipefunc 0.79.0

recipe/recipe.yaml
=> Bump to 0.80.0

recipe/recipe.yaml
=> Bump to pipefunc 0.80.1

build-locally.py, pixi.toml, recipe/recipe.yaml
=> Bump to pipefunc 0.82.0

recipe/recipe.yaml
=> Bump to pipefunc 0.82.1

recipe/recipe.yaml
=> Bump to pipefunc 0.82.3

recipe/recipe.yaml
=> Bump to pipefunc 0.83.0
